### PR TITLE
-dont_show dont not work as intended

### PR DESCRIPTION
**Pull request by kuldeepdhaka**
Reference: https://github.com/AlexeyAB/darknet/issues/2910

### CODE REVIEW

**Comment by kriyeng** [comment]
Hi @kuldeepdhaka !
Thank you for your contribution! I rebased the source to the original repo. Everything is up to date now.

AlexeyAB says that's solved now. 
Could you check if it works well now?

Thank you!

**Comment by kuldeepdhaka** [comment]
@kriyeng Yes it fixed in main repo but the code did not make it to feature/google-colab.

**Comment by kuldeepdhaka** [comment]
I dont see "show_image_mat(mat, "mat");" in branch feature/google-colab anymore and it was reported as the reason of the issue of causing `Using -dont_show parameter still causes (mat:19060): Gtk-WARNING **: cannot open display: #2910` (similar issue for me as well).
Ran my collaboratory code with new code (after building test inference of video and picture but not tested traning) and it work fine.
So i guess, it is safe to steam ahead!

**Comment by kriyeng** [comment]
Great!! 
Thanks again for your contribution!!

Closing: Works fine after rebase the original repo.

**Pull request closed without merging**
